version: '3.9'
services:
  gitlab: 
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: | 
      external_url 'http://127.0.0.1:9999'
      gitlab_rails['gitlab_shell-ssh_port'] = 2222
    port:
      - 9999:9999
      - 2222:2222
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

      





      Password: aHhRWz3X2tsMCh0MS0ir7gqsT/o6zB7CG/7XyWx0hUI=